version: "3"

services:
  vueshop:
    container_name: vueshop
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec foreman start"
    env_file:
      - .env
    volumes:
      - .:/vueshop
    ports:
      - "3000:3000"
    depends_on:
      - vueshop-db
    stdin_open: true
    tty: true
    links:
      - vueshop-db
  vueshop-db:
    container_name: vueshop-db
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - .:/vueshop
    environment:
      MYSQL_ROOT_PASSWORD: Aa@123123
      MYSQL_DATABASE: vueshop
      MYSQL_USER: vueshop
      MYSQL_PASSWORD: Aa@123123
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
